extends:
  - standard
  - prettier
env:
  node: true
  mocha: true
parser: typescript-eslint-parser
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
overrides:
  - files:
      - "**/*.ts"
      - "**/*.tsx"
    rules:
      no-unused-vars: 0
      no-undef: 0